### ISSUE TITLE
minimum requirement

### ISSUE THREAD

**Issue by arist0v** [snorp/insteon-adapter#3]
hi, does the insteon device will work directly with the webthings gateway, or did you need an insteon hub or something else ?

**Comment by snorp** [comment]
You need a USB adapter. I've used these:

https://www.smarthome.com/insteon-2448a7-portable-usb-adapter.html
https://www.smarthome.com/powerlinc-modem-insteon-2413u-usb-interface-dual-band.html

**Comment by arist0v** [comment]
thank you for the informations
